### ISSUE TITLE
Missing coins

### ISSUE THREAD

**Issue by joshakatz** [AndrejJurkin/nova-osx#6]
I have NOVA running on two Macs and it's been great but on one of my computers NOVA can't find some of the coins the other one can.  Specifically SUB and REQ.

**Comment by AndrejJurkin** [comment]
Thanks for pointing it out! CoinMarketCap API has been slightly changed that is the reason why this issue has been occurring lately. It will be fixed in the next release.

**Comment by AndrejJurkin** [comment]
Fixed in 0.1.5
